language: java
sudo: false # faster builds

jdk:
    - oraclejdk8
    - openjdk8
before_script:  
    - chmod +x mvnw

script:
    - mvn clean package
    - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
